### ISSUE TITLE
WP Block parser missing code ?

### ISSUE THREAD

**Issue by kuuak** [superhuit-agency/superstack#15]
While upgrading ECA site, I noticed in the [block-parser.php](https://github.com/superhuit-agency/superstack/blob/main/wordpress/theme/lib/blocks/block-parser.php) file that some code was missing in the boilerplate.

I wonder if the missing code has been intentionaly remove or if we forgot to include it (as it has maybe been included for specific sites only)

see https://github.com/superhuit-agency/theatre-vidy/commit/ae2cb18de2ce797f0d65c6305b055fd88fc58af9

**Comment by kuuak** [comment]
cc. @charl0tee @hsmio @snugglejuice

**Comment by hsmio** [comment]
I don't think this is on purpose. I will let @charl0tee and @snugglejuice confirm too.

**Comment by kuuak** [comment]
OK good then 👍
