### ISSUE TITLE
Use new GraphQL for ACF plugin

### ISSUE THREAD

**Issue by charl0tee** [superhuit-agency/superstack#4]
The old wp-graphql/wp-graphql-acf plugin seemed to now be in => https://github.com/wp-graphql/wpgraphql-acf

Here is the upgrade guide -> https://acf.wpgraphql.com/upgrade-guide/

**Comment by kuuak** [comment]
@charl0tee The superstack doesn't include (for now at least) ACF nor wp-graphql-acf plugins.

I guess because of a choice to simpliy the stack and have less things to remove if not needed.

I feel therefore that this issue can be closed, be keep in mind to include the new plugin in future projects

**Comment by charl0tee** [comment]
@kuuak You're completely right ! I close the issue ;)
