### ISSUE TITLE
Update Wordpress to 6.5

### ISSUE THREAD

**Issue by charl0tee** [superhuit-agency/superstack#6]
We're currently on WP 6.4. It seems there are some issues with the core blocks (especially `core/paragraph` that doesn't seem to save the content with the `content` attribute anymore)

**Comment by kuuak** [comment]
@charl0tee The problem was that wordpress changed how the content was saved. The WpGraphql-gutenberg plugin needed to be updated as well.

See https://github.com/pristas-peter/wp-graphql-gutenberg/issues/206
